name: SpringBoot Test Action(Run Jar File Bakend)
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true
      - name: info
        run: pwd && mvn -v && java -version && ifconfig
      - name: exex
        working-directory: /home/runner/work/mybatisplus-hikariCP/mybatisplus-hikariCP/target
        run :
          - touch my.log
          - nohup java -jar hikaricp-demo-0.0.1-SNAPSHOT.jar >/dev/null &

