name: SpringBoot Test Action
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build with Maven
        run: mvn clean package -Dmaven.test.skip=true
      - name: Show Resulu path
        run : pwd && cd target && ls -al&& java -version&&ifconfig
      - name: run app
        run: java -jar hikaricp-demo-0.0.1-SNAPSHOT.jar
